name: cosmetics
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  dio: ^5.9.2
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10
  geocoding: ^4.0.0
  google_maps_flutter: ^2.6.1
  pin_code_fields: ^8.0.1
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: 'assets/images/login_logo.png'
  min_sdk_android: 21

  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: SegoeUI
      fonts:
        - asset: assets/fonts/segoe/segoe_uI.ttf
        - asset: assets/fonts/segoe/segoe_uI_bold.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/montserrat-Italic-variablefont_wght.ttf
        - asset: assets/fonts/montserrat/montserrat-variablefont_wght.ttf
